// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rest.proto

package com.proto.rest;

public interface ProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.Product)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 stock = 3;</code>
   * @return The stock.
   */
  int getStock();

  /**
   * <code>.product.Type type = 4;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.product.Type type = 4;</code>
   * @return The type.
   */
  com.proto.rest.Type getType();
}
