// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rest.proto

package com.proto.rest;

public final class Rest {
  private Rest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_Products_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_Products_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_Product_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_Basket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_Basket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nrest.proto\022\007product\"-\n\010Products\022!\n\007pro" +
      "duct\030\001 \003(\0132\020.product.Product\"O\n\007Product\022" +
      "\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\r\n\005stock\030\003 \001(\005" +
      "\022\033\n\004type\030\004 \001(\0162\r.product.Type\"F\n\006Basket\022" +
      "\n\n\002id\030\001 \001(\005\022!\n\007product\030\002 \003(\0132\020.product.P" +
      "roduct\022\r\n\005total\030\003 \001(\002*7\n\004Type\022\007\n\003NON\020\000\022\016" +
      "\n\nELECTRONIC\020\001\022\013\n\007FASHION\020\002\022\t\n\005SPORT\020\003B\022" +
      "\n\016com.proto.restP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_product_Products_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_product_Products_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_Products_descriptor,
        new java.lang.String[] { "Product", });
    internal_static_product_Product_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_product_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_Product_descriptor,
        new java.lang.String[] { "Id", "Name", "Stock", "Type", });
    internal_static_product_Basket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_product_Basket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_Basket_descriptor,
        new java.lang.String[] { "Id", "Product", "Total", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
